In [12]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/Algerian_forest_fires_dataset.csv")
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire

In [13]:
print("Dataset shape:",df.shape)
print("-" * 50)
df.info()

Dataset shape: (247, 14)
--------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          246 non-null    str
 1   month        245 non-null    str
 2   year         245 non-null    str
 3   Temperature  245 non-null    str
 4    RH          245 non-null    str
 5    Ws          245 non-null    str
 6   Rain         245 non-null    str
 7   FFMC         245 non-null    str
 8   DMC          245 non-null    str
 9   DC           245 non-null    str
 10  ISI          245 non-null    str
 11  BUI          245 non-null    str
 12  FWI          245 non-null    str
 13  Classes      244 non-null    str
dtypes: str(14)
memory usage: 27.1 KB

In [15]:
# Create a fresh copy to work safely
df_clean = df.copy()

# 1. Clean up whitespace from the column names to avoid hidden space issues
df_clean.columns = df_clean.columns.str.strip()

# 2. Assign Regions based on your exact layout
# Everything up to index 121 is Bejaia (0)
df_clean.loc[:121, "Region"] = 0

# Everything from index 122 onwards is Sidi-Bel Abbes (1)
df_clean.loc[122:, "Region"] = 1

# 3. DROP the garbage rows FIRST (this removes the NaN values that caused the error)
# Drop any row where the 'day' column is completely missing/NaN
df_clean = df_clean.dropna(subset=['day']).reset_index(drop=True)

# Drop the row where 'day' is literally written out as the text string "day"
df_clean = df_clean[df_clean['day'] != 'day'].reset_index(drop=True)

# 4. NOW it is safe to convert Region into a clean integer type!
df_clean["Region"] = df_clean["Region"].astype(int)

# Let's check the shape and verify the boundary point transitions beautifully
print("Cleaned Dataset Shape:", df_clean.shape)
df_clean.iloc[120:125]

Cleaned Dataset Shape: (245, 15)

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
120,29,9,2012,26,80,16,1.8,47.4,2.9,7.7,0.3,3,0.1,not fire,0
121,30,9,2012,25,78,14,1.4,45,1.9,7.5,0.2,2.4,0.1,not fire,0
122,Sidi-Bel Abbes Region Dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
123,1,6,2012,32,71,12,0.7,57.1,2.5,8.2,0.6,2.8,0.2,not fire,1
124,2,6,2012,30,73,13,4,55.7,2.7,7.8,0.6,2.9,0.2,not fire,1

In [16]:
# Remove the stray region title row sitting at index 122
df_clean = df_clean[df_clean['day'] != 'Sidi-Bel Abbes Region Dataset'].reset_index(drop=True)

# Let's inspect the boundary rows one last time to ensure it's 100% flawless
df_clean.iloc[120:124]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
120,29,9,2012,26,80,16,1.8,47.4,2.9,7.7,0.3,3,0.1,not fire,0
121,30,9,2012,25,78,14,1.4,45,1.9,7.5,0.2,2.4,0.1,not fire,0
122,1,6,2012,32,71,12,0.7,57.1,2.5,8.2,0.6,2.8,0.2,not fire,1
123,2,6,2012,30,73,13,4,55.7,2.7,7.8,0.6,2.9,0.2,not fire,1

In [18]:
df = df.dropna().reset_index(drop=True)

In [19]:
df = df[df['day'].str.strip() != 'day'].reset_index(drop=True)

In [20]:
for col in df.columns:
    if df[col].dtype == 'object' or df[col].dtype == 'str':
        df[col] = df[col].str.strip()

In [21]:
# Strip any accidental whitespace from column names first
df.columns = df.columns.str.strip()

# Convert date and integer columns
int_cols = ['day', 'month', 'year', 'Temperature', 'RH', 'Ws']
df[int_cols] = df[int_cols].astype(int)

# Convert float columns (indices)
float_cols = ['Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI', 'FWI']
df[float_cols] = df[float_cols].astype(float)

In [22]:
df_clean.iloc[120:124]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
120,29,9,2012,26,80,16,1.8,47.4,2.9,7.7,0.3,3,0.1,not fire,0
121,30,9,2012,25,78,14,1.4,45,1.9,7.5,0.2,2.4,0.1,not fire,0
122,1,6,2012,32,71,12,0.7,57.1,2.5,8.2,0.6,2.8,0.2,not fire,1
123,2,6,2012,30,73,13,4,55.7,2.7,7.8,0.6,2.9,0.2,not fire,1

In [23]:
print("Dataset shape:",df.shape)
print("-" * 50)
df.info()

Dataset shape: (243, 14)
--------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    int64
 1   month        243 non-null    int64
 2   year         243 non-null    int64
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    int64
 6   Rain         243 non-null    float64
 7   FFMC         243 non-null    float64
 8   DMC          243 non-null    float64
 9   DC           243 non-null    float64
 10  ISI          243 non-null    float64
 11  BUI          243 non-null    float64
 12  FWI          243 non-null    float64
 13  Classes      243 non-null    str
dtypes: float64(7), int64(6), str(1)
memory usage: 26.7 KB

In [24]:
# Create a Region column initialized to 0 (First Region: Bejaia)
df['Region'] = 0

# Assign 1 to the rows after the middle separator (Second Region: Sidi Bel-Abbes)
# Since the split happens exactly at row index 122, we mark everything from 122 onwards as 1
df.loc[122:, 'Region'] = 1

# Convert it to an integer type
df['Region'] = df['Region'].astype(int)

In [25]:
print("Dataset shape:",df.shape)
print("-" * 50)
df.info()

Dataset shape: (243, 15)
--------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    int64
 1   month        243 non-null    int64
 2   year         243 non-null    int64
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    int64
 6   Rain         243 non-null    float64
 7   FFMC         243 non-null    float64
 8   DMC          243 non-null    float64
 9   DC           243 non-null    float64
 10  ISI          243 non-null    float64
 11  BUI          243 non-null    float64
 12  FWI          243 non-null    float64
 13  Classes      243 non-null    str
 14  Region       243 non-null    int64
dtypes: float64(7), int64(7), str(1)
memory usage: 28.6 KB

In [27]:
# 1. Add the Region feature
df['Region'] = 0
df.loc[122:, 'Region'] = 1
df['Region'] = df['Region'].astype(int)

# 2. Drop completely empty rows
df = df.dropna().reset_index(drop=True)

# 3. Drop the redundant text header row from the middle
df = df[df['day'].astype(str).str.strip() != 'day'].reset_index(drop=True)

# 4. Clean up whitespaces from column names and string values
df.columns = df.columns.str.strip()
for col in df.columns:
    if df[col].dtype == 'object' or df[col].dtype == 'str':
        df[col] = df[col].str.strip()

# 5. Convert everything to the correct numerical types
int_cols = ['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Region']
df[int_cols] = df[int_cols].astype(int)

float_cols = ['Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI', 'FWI']
df[float_cols] = df[float_cols].astype(float)

In [28]:
df['Classes'].value_counts()

Classes
fire        137
not fire    106
Name: count, dtype: int64

In [29]:
# To transform the text labels into binary number:

# Map 'fire' to 1 and 'not fire' to 0
df['Classes'] = df['Classes'].map({'fire': 1, 'not fire': 0})

print(df['Classes'].value_counts())

Classes
1    137
0    106
Name: count, dtype: int64

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    int64
 1   month        243 non-null    int64
 2   year         243 non-null    int64
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    int64
 6   Rain         243 non-null    float64
 7   FFMC         243 non-null    float64
 8   DMC          243 non-null    float64
 9   DC           243 non-null    float64
 10  ISI          243 non-null    float64
 11  BUI          243 non-null    float64
 12  FWI          243 non-null    float64
 13  Classes      243 non-null    int64
 14  Region       243 non-null    int64
dtypes: float64(7), int64(8)
memory usage: 28.6 KB

In [31]:
import os

# Create the processed directory if it doesn't exist yet
processed_path = "../data/processed"
os.makedirs(processed_path, exist_ok=True)

# Save the clean DataFrame without the row index numbers
df.to_csv(f"{processed_path}/cleaned_algerian_fire_data.csv", index=False)

print("Cleaned dataset successfully saved to data/processed/cleaned_algerian_fire_data.csv!")

Cleaned dataset successfully saved to data/processed/cleaned_algerian_fire_data.csv!